name: Keep Render App Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint with retries
        run: |
          for i in {1..5}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://safehouse-bot.onrender.com/api/health || true)
            if [ "$STATUS" -eq 200 ]; then
              echo "Health check succeeded with status $STATUS"
              exit 0
            else
              echo "Attempt $i failed with status $STATUS. Retrying in 15s..."
              sleep 15
            fi
          done
          echo "All retries failed. Exiting."
          exit 1
